using Microsoft.Extensions.Configuration;
using SharedDomain;
using System.Text.Json;

namespace WebhookService.Services;

public interface IPayloadParserService
{
    IEnumerable<NormalizedEvent> ParsePayload(string rawPayload);
}

public class PayloadParserService : IPayloadParserService
{
    private readonly string? _pageId;

    public PayloadParserService(IConfiguration configuration)
    {
        _pageId = configuration["Facebook:PageId"];
    }

    public IEnumerable<NormalizedEvent> ParsePayload(string rawPayload)
    {
        var events = new List<NormalizedEvent>();

        try
        {
            using var jsonDocument = JsonDocument.Parse(rawPayload);
            var root = jsonDocument.RootElement;

            if (!root.TryGetProperty("entry", out var entries))
            {
                return events;
            }

            foreach (var entry in entries.EnumerateArray())
            {
                if (entry.TryGetProperty("messaging", out var messagings))
                {
                    foreach (var messaging in messagings.EnumerateArray())
                    {
                        var senderId = messaging.GetProperty("sender").GetProperty("id").GetString();
                        if (messaging.TryGetProperty("message", out var messageObj) && messageObj.TryGetProperty("text", out var textObj))
                        {
                            events.Add(new NormalizedEvent
                            {
                                Source = "Messenger",
                                SenderId = senderId ?? "unknown",
                                Content = textObj.GetString() ?? string.Empty,
                                RawPayload = rawPayload
                            });
                        }
                    }

                    continue;
                }

                if (!entry.TryGetProperty("changes", out var changes))
                {
                    continue;
                }

                foreach (var change in changes.EnumerateArray())
                {
                    if (!change.TryGetProperty("value", out var valueObj) ||
                        !valueObj.TryGetProperty("item", out var itemObj))
                    {
                        continue;
                    }

                    var itemType = itemObj.GetString();
                    if (!string.Equals(itemType, "comment", StringComparison.OrdinalIgnoreCase))
                    {
                        continue;
                    }

                    if (valueObj.TryGetProperty("verb", out var verbObj) &&
                        !string.Equals(verbObj.GetString(), "add", StringComparison.OrdinalIgnoreCase))
                    {
                        // Ignore edit/remove events to avoid duplicate automations.
                        continue;
                    }

                    if (!valueObj.TryGetProperty("comment_id", out var commentIdObj))
                    {
                        continue;
                    }

                    // Facebook may use different owner prefixes for the same top-level post/photo object.
                    // Keep top-level comments whose parent and post point to the same underlying object,
                    // but still ignore replies to another comment.
                    var parentId = valueObj.TryGetProperty("parent_id", out var parentIdObj) ? parentIdObj.GetString() : null;
                    var postId = valueObj.TryGetProperty("post_id", out var postIdObj) ? postIdObj.GetString() : null;
                    if (IsReplyToAnotherComment(parentId, postId))
                    {
                        continue;
                    }

                    string? senderId = null;
                    string? senderName = null;
                    if (valueObj.TryGetProperty("from", out var fromObj))
                    {
                        senderId = fromObj.GetProperty("id").GetString();
                        senderName = fromObj.GetProperty("name").GetString();
                    }

                    if (!string.IsNullOrWhiteSpace(_pageId) && string.Equals(senderId, _pageId, StringComparison.Ordinal))
                    {
                        // Ignore comments generated by the page itself to prevent loops.
                        continue;
                    }

                    var commentId = commentIdObj.GetString() ?? string.Empty;
                    var message = valueObj.TryGetProperty("message", out var msgObj) ? msgObj.GetString() : string.Empty;

                    events.Add(new NormalizedEvent
                    {
                        EventId = commentId,
                        PlatformEventId = commentId,
                        Source = "PageComment",
                        SenderId = senderId ?? "unknown",
                        SenderName = senderName ?? "unknown",
                        Content = message ?? string.Empty,
                        RawPayload = rawPayload
                    });
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error parsing payload: {ex.Message}");
        }

        return events;
    }

    private static bool IsReplyToAnotherComment(string? parentId, string? postId)
    {
        if (string.IsNullOrWhiteSpace(parentId) || string.IsNullOrWhiteSpace(postId))
        {
            return false;
        }

        if (string.Equals(parentId, postId, StringComparison.Ordinal))
        {
            return false;
        }

        return !string.Equals(GetObjectId(parentId), GetObjectId(postId), StringComparison.Ordinal);
    }

    private static string GetObjectId(string compositeId)
    {
        var separatorIndex = compositeId.LastIndexOf('_');
        return separatorIndex >= 0 ? compositeId[(separatorIndex + 1)..] : compositeId;
    }
}
